### ISSUE TITLE
Transaction details regarding baker are still referring to GTU instead of CCD

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-android#101]
**Bug Description**
Transaction details regarding baker are still referring to GTU instead of CCD. This is the case for block rewards, baking rewards, stake amounts.
**Steps to Reproduce**

1. Create account and ID through Mobile Wallet.
2. Add baker through the command line tool.
3. Try to re-stake. 
4. Observe rewards details as they appear.

**Expected Result**
Transaction details should refer to CCD amounts.

**Actual Result**
Transaction details are referring to GTU amounts.

**Versions**
- Software Version: Stagenet 1.2.6 
- OS: Android 10
- Browser
- Mobile device, if applicable: Samsung Galaxy J6

**Attachments:**

_Update baker stakes:_
<img width="247" alt="Update_baker_stake" src="https://user-images.githubusercontent.com/98821384/153161527-a98d32aa-6b07-4855-942e-ac794cb521d3.png">

_Block rewards:_
<img width="240" alt="Block_rewards" src="https://user-images.githubusercontent.com/98821384/153161564-62ebd2fe-092b-429f-b044-2268c4b10440.png">

_Baker rewards:_
<img width="245" alt="Baker_rewards" src="https://user-images.githubusercontent.com/98821384/153161585-78bd9da4-49dd-4417-bd31-c5a56dbe6a7d.png">

**Comment by abizjak** [comment]
This is a wallet-proxy/backend provided string. Fixed in this PR https://github.com/Concordium/concordium-wallet-proxy/pull/38/files

**Comment by mh-concordium** [comment]
The fix was verified with Mobile Wallet 1.2.6 on stagenet and testnet. Labels that were showed in the transaction details were correct.
