### ISSUE TITLE
Screen rotations to landscape mode provide low usability and in some cases crash application

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-android#109]
**Bug Description**
Screen rotations are not convenient for Mobile Wallet. Application should be locked to portrait mode and it should not be possible to switch to landscape mode.

**Steps to Reproduce**
Screen rotations provide low usability on:
- Carousel intro 
- Viewing list of accounts
- Sending CCDs
- Shielded balance.

**Expected Result**
Mobile wallet should be locked to portrait mode and it should not be possible to switch to landscape mode.

**Actual Result**
Landscape mode is available.

***Versions**
- Software Version: Stagenet 2.0
- OS: Android 11
- Browser: N/A
- Mobile device: Google Pixel 4a

**Comment by jensvesti** [comment]
I agree. It has been like this from the beginning. I'll lock it.

**Comment by mh-concordium** [comment]
Verified.

**Versions**
- Software Version: Testnet 2.0.1 (71)
- OS: Android 11
- Browser: N/A
- Mobile device: Pixel 4a
