### ISSUE TITLE
Introduction carousel interrupted by home button

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-android#110]
**Bug Description**
User starts the application for the first time and swipes through carousel. If user stops carousel introduction with home button, returning back to application doesn't return to where the introduction stopped.

**Steps to Reproduce**
1. Install the application and run the initial account creation.
2. After the introduction carousel started, swipe to the third page and then press home button to put the application in the background.
3. Reopen application.

**Expected Result**
Carousel should continue where it stopped.

**Actual Result**
Accounts page is opened. Introduction carousel can't be started again.

Video:

https://user-images.githubusercontent.com/98821384/155716740-f56c64ea-a98a-419a-9bb8-6654ce92a1fc.mp4

**Versions**
- Software Version: Stagenet 2.0
- OS: Android 11
- Browser: N/A
- Mobile device: Google Pixel 4a

**Comment by jensvesti** [comment]
@mh-concordium @jens-concordium  Not a trivial thing to change. Similar issue has always been there: The "Are you new to Concordium?" screen is only shown once, and never again. 
Is this a priority bug, and in that case, how about the "Are you new to Concordium?"? We cannot have one without the other.

**Comment by jens-concordium** [comment]
@mh-concordium, @concordium-cl I think it would be okay to wait fixing this. What do you think?

**Comment by concordium-cl** [comment]
I've moved it to the backlog.

**Comment by concordium-cl** [comment]
Won't do.
