### ISSUE TITLE
Initial flow is interrupted at creating password - application can't recover, it needs to be reinstalled

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-android#112]
**Bug Description**
Initial flow is interrupted at creating password. This can easily happen if user is distracted, locks phone or simply receives a call.

**Steps to Reproduce**

1. Start MW application right after it was installed 
2. Switch to other application or just press home button.
3. Get back to Mobile Wallet.
4.  App crashes after inserting password many times or just by pressing continue without any password provided.

**Expected Result**
Application should be able to recover, initiate start up again and ask for the first password.

**Actual Result**
Application can't start again, it seems that its locked up between 2 passwords. Attempt to insert any password results with just asking another password. Attempt to use empty string as a password crushes application.

Video:

https://user-images.githubusercontent.com/98821384/155727824-c5381037-1f76-4d41-8311-a269500a9e59.mp4

**Versions**
- Software Version: Stagenet 2.0
- OS: Android 11
- Browser: N/A
- Mobile device: Google Pixel 4a

**Comment by concordium-cl** [comment]
Will move.
