### ISSUE TITLE
Notifications are not appearing for shielded transfers in any of the cases defined

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-android#113]
**Bug Description**
As proposed there should be notification in following situations:

1. When user opens a page with all accounts while one or more accounts contain shielded balance, notification about shielded balance will appear.
2. If user receives shielded transfer, notification will appear.
3. User will have capability to choose three options when the notification appears:
- Show Shielded balance for <accountName> - Button will route the user to the corresponding shielded balance.
- Remind me later - Notification will appear on the next shielded transaction. (Or next day/month?)
- Don't show this again - Notification won't show ever again.

**Steps to Reproduce**
I was not able to see notification in any of the cases above.
**Expected Result**

**Actual Result**
Defined above in description.

**Versions**
- Software Version: Stagenet 2.0
- OS: Android 11
- Browser: N/A
- Mobile device: Google Pixel 4a

**Comment by jensvesti** [comment]
@jens-concordium @mh-concordium 
"User will have capability to choose three options when the notification appears:"
There are only two options in Figma as well as the iOS implementation. I prefer to keep it at this for now.

**Comment by jens-concordium** [comment]
@jensvesti, sounds fair! I think the third option was from a discussion in Slack a while ago, but I can't recall the details. If we only have two options on iOS as well, I think it's a good idea to keep it consistent.

**Comment by jens-concordium** [comment]
@concordium-cl, I agree with 1., if it's possible to do without too much hassle.

Regarding 2: Had it ever had any shielded transactions? If there has been some transactions on it, it will likely appear as if there is something on the shielded balance.

**Comment by concordium-cl** [comment]
Regarding 2.: No. The first account in the list triggers the message, even if it never had a shielded balance.

- create account 2 with balance 0 and do not touch anything in the context of shielded balance
- account appears at top of account list
- export
- reinstall app 
- import
--> message that account 2 has a shielded balance

- create account 1 with balance 0 and do not touch anything in the context of shielded balance
- account appears at top of account list
- export
- reinstall app 
- import
--> message that account 1 has a shielded balance
--> no message that account 2 has a shielded balance

**Comment by concordium-cl** [comment]
Verified in CCD app v. 2.0.0 (74), Huawei Y6s, Android 9.
1 Fixed.
2. Fixed.
