### ISSUE TITLE
Delegation: Stopping a delegation

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-android#118]
**Task description**
Besides registering and updating a delegation, the user must also be able to stop their delegation again.

In practice, this is done by making a ConfigureDelegation transaction, setting the amount to 0. From the users perspective, there will be a "Stop delegation" on the [delegation status page](https://github.com/Concordium/concordium-reference-wallet-android/issues/115). 

A delegation can only be stopped if there a no pending decreases to the delegation amount, or if there has not been a "Stop delegation" transaction already, effectively decreasing the amount to 0. In those cases, the "Stop delegation" button will not be active, as shown in **Delegation status scenario 3.**

In Flow 5 in Figma, the "Stop delegation" transaction can be seen. The first page is a carousel with some info on what it means to stop a delegation, and how it will be affected by a cool down period. Else it's just page 2 and 3 showing the transaction slip with an overview before an after submission. Lastly, before returning to the delegation status page as seen in **Delegation status scenario 4**, there will be a notification reminding the user about the cool down.

**Comment by mh-concordium** [comment]
Verified.
3.0.5 (89)
