### ISSUE TITLE
Align build versioning format across iOS and Android

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-android#127]
**Description**
We would like to see the full version name in the application build that is released if possible. Would it be ok that we agree on the build versions format that is unified and visible only in "About" page:

2.0.0 (70) - Stagenet
2.0.1 (71) - Testnet
2.0.1

For Mainnet, we wouldn't put anything but version number that was the last one, in the above example 2.0.1 (the same way it is today).

**Expected Result**
Version number in format as proposed above visible only on About page.

**Actual Result**
![image (1)](https://user-images.githubusercontent.com/98821384/156573180-1b49e784-0f00-44f3-8733-b6feef3988ce.png)

**Versions**
For both iOS and Android.

**Comment by mh-concordium** [comment]
Please align with @ruxandra-constantinescu how to format and number builds.

**Comment by concordium-cl** [comment]
Format is not aligned. Each platform took a piece from the suggestion of 
**2.0.1 (71) - Testnet** but unfortunately not the same piece.
1. iOS shows version as 2.0.0 (37)
2. Android shows version as 2.0.3 - Testnet

While 1. is acceptable, it is impossible to keep track of Android versions during testing if the build number is missing. 

Expected fix: Show version as 2.0.3 (73).

**Comment by concordium-cl** [comment]
Verified in CCD app v. 2.0.0 (74), Huawei Y6s, Android 9.
