### ISSUE TITLE
Wallet-proxy URL in the mainnet app

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-android#13]
**Description**
Currently, the mainnet app points to the testnet backend. The wallet-proxy URL in the mainnet app must be changed before release.

Align with @jens-concordium, @smh1001, @concordium-cl before making this final change.

**Comment by abizjak** [comment]
@concordium-cl should this be considered done now, since the mainnet app has been released?

**Comment by jens-concordium** [comment]
@abizjak, Yes, I think we can consider it done.

**Comment by abizjak** [comment]
Close it then please.
