### ISSUE TITLE
Delegation/Baking: Fill in carousel content

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-android#131]
**Task description**

This is a placeholder task for now. Will be filled out when then content for the carousels is ready.

**Comment by mh-concordium** [comment]
Verified.
Version 3.0.0 (84).

**Comment by mh-concordium** [comment]
Validate Baking carousel comparing with Figma.

**Comment by mkmks** [comment]
I didn't find any differences of the baking flow with what's specified in Figma, except for the behaviour already reported in #170.
