### ISSUE TITLE
Baker id is not resolved

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-android#132]
**Bug Description**
If a mobile wallet contains account with baker, baker id is not correctly resolved.
Id from screenshot should be 5109.

**Steps to Reproduce**
Use account created with mobile to have a baker on Testnet.

**Expected Result**
Baker Id should be 5109.

**Actual Result**
<img width="295" alt="BakerID not visible" src="https://user-images.githubusercontent.com/98821384/157427678-a6fd202d-0ec4-4659-8a56-43c557b7f01d.png">

**Versions**
- Software Version: Testnet 2.0.1 (71)
- OS: Android 11
- Browser: N/A
- Mobile device: Pixel 4a

**Comment by jensvesti** [comment]
@mh-concordium I don't have an account with baker. But, the fix is simple so it might work. If not, I need an account with baker.

**Comment by concordium-cl** [comment]
Verified in CCD app Android 2.0.3 (73).
