### ISSUE TITLE
Page titles are inconsistent

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-android#133]
**Bug Description**
Tittle of Accounts page and More page is just "Wallet".

**Steps to Reproduce**
Tap through pages on MW.

**Expected Result**
I would think that each of the pages would have their own heading as in the menu.

**Actual Result**
<img width="319" alt="Heading" src="https://user-images.githubusercontent.com/98821384/157440924-b47a2962-9ee6-4acd-ab53-db09209f16d2.png">

<img width="353" alt="More" src="https://user-images.githubusercontent.com/98821384/157440929-de33e0fd-8399-454c-b6ef-3296b9a9b1fb.png">

**Versions**
- Software Version: Testnet 2.0.1 (71)
- OS: Android 11
- Browser: N/A
- Mobile device: Pixel 4a

**Comment by ZB-concordium** [comment]
Software Version: Testnet 3.0.4(88)
OS: Android 12
Mobile device: Samsung S21 Ultra
