### ISSUE TITLE
Shielded icons should be removed

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-android#134]
**Bug Description**
After restoring from backup, shield icons appear next to both balances. This is the case if a backup that was restored contained shielded amount.

**Steps to Reproduce**

- Create account and shield some CCDs.
- Make a backup.
- Reinstall wallet.
- Restore from backup.

**Expected Result**
Balances on accounts page should not show +shieldIcon

**Actual Result**
<img width="294" alt="Shield icons" src="https://user-images.githubusercontent.com/98821384/157445677-ff40c7f8-b4bf-4be5-8454-85570c88dd7c.png">

**Versions**
- Software Version: Testnet 2.0.1 (71)
- OS: Android 11
- Browser: N/A
- Mobile device: Pixel 4a

**Comment by concordium-cl** [comment]
Verified in CCD app Android v. 2.0.3 (73).
