### ISSUE TITLE
Add a README

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-reference-wallet-android#14]
**Task description**

Add a README to the repository to briefly explain what it contains, as well as how to build, what dependencies are, how to test, and how to contribute.

**Comment by pablozsc** [comment]
Do you know if it will be possible/allowed for third party to create a new wallet software also? Or will there only be officials?

**Comment by abizjak** [comment]
@pablozsc it is certainly allowed that others create new wallets for the Concordium blockchain. This is also why we named the repositories "reference" wallet, with the idea that this is a reference that can be built upon or used as a guidance when building other wallets.

**Comment by abizjak** [comment]
Closed by #16
