### ISSUE TITLE
Handle too large delegation amounts when changing target pools

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-android#141]
**Task description**

If a delegator has a current delegation amount that is too large for a new target pool, the MW should handle the situation in a way that is understandable for the user. There are two scenarios where a current delegation amount would breach a new target pools limit:

1. A delegators amount is currently in lockdown, and the delegator has chosen a new target pool ID with a limit that would be breach with the amount currently in lockdown. In this case the error message should be slightly different than it usually is. `Pool limit will be breached` --> `Your delegation amount is too large for this pool.` If possible it would also be nice to highlight the currently delegated amount at the top of the screen. 

2. A delegator has chosen a new target pool and the currently delegated amount (no cooldown) would breach the new pools limit. As the node would just reject a transaction where the current delegation amount would breach a new target pools limit (even though the user also lowered the amount in the same transaction), the user should be met with a notification explaining the situation. The notification should either let the user lower the delegation amount, stop the delegation or just cancel the flow. 

Both scenarios can be see in F**low7: Update delegation transaction, Scenario 6: Current delegation amount will breach new targets limits**

**Comment by rimbi** [comment]
The change `Pool limit will be breached` --> `Your delegation amount is too large for this pool.` is missing.

Verified with the Android MW version 3.0.11 (95)

**Comment by XOOPsoft** [comment]
Fixed in version 3.0.12 (96)

**Comment by rimbi** [comment]
Old text is still there:
![WhatsApp Image 2022-06-22 at 9 25 22 AM](https://user-images.githubusercontent.com/51825/174958376-ee208f68-9bd7-46f5-9a9b-b44e1cf9b376.jpeg)

Verified with version 3.0.12 (96)

**Comment by XOOPsoft** [comment]
On the screenshot you are not in cooldown (amount is not locked)
When not in cooldown the text should be "Pool limit will be breached"
If you are in cooldown (locked amount), then the text should be "Your delegation amount is too large for this pool"
So the app is correct in the screenshot.

Please see Figma here:
https://www.figma.com/file/pUlYPsHRU0Hvm0NoGIvxrv/Mobile-Wallet?node-id=3495%3A17217
and here:
https://www.figma.com/file/pUlYPsHRU0Hvm0NoGIvxrv/Mobile-Wallet?node-id=4762%3A20593

**Comment by rimbi** [comment]
@jens-concordium can you verify @XOOPsoft 's expectation above, please?

**Comment by jens-concordium** [comment]
I think so. Maybe I even agreed with @XOOPsoft and @Niljak that it should be like that. Was that how we ended up doing it, @XOOPsoft and @Niljak?

**Comment by XOOPsoft** [comment]
No, I don't recall that we talked about showing the message on the previous page.
I have just created a new release 3.0.0 (97)
All scenarios should be in place now.

**Comment by rimbi** [comment]
verified with 3.0.0 (97)

**Comment by rimbi** [comment]
Verified with release 3.0.0 (98)
