### ISSUE TITLE
Notify the delegator if the baker reduces the stake

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-android#148]
**Description**
If the pool size reduces because of the baker reduced the stake, effective stake will be reduced and thus, delegators will receive less rewards. It would be nice to inform delegators that their effective stake is reduced.
**Steps to Reproduce**

**Expected Result**
Notification to a delegator would be a nice thing to have.

**Actual Result**
Delegators effective stake will be reduced and thus, rewards will be lower.

**Versions**
- Software Version: 3.0.0 (82)
- OS: Android

**Comment by concordium-cl** [comment]
Won't do.
