### ISSUE TITLE
"Send all" uses account total instead of disposable

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium-reference-wallet-android#151]
**Bug Description**
The "Send all" button uses account total instead of disposable.

**Steps to Reproduce**
1. Use an account that has scheduled transfers or is delegating so that `disposable < total`
2. Click on **Send**
3. Click on **Send all**
4. Look at the proposed amount to send

**Expected Result**
`disposable balance - transaction cost`

**Actual Result**
`total balance - transaction cost`

**Versions**
- Software Version: 3.0.0 (84)
- OS: Android
- Mobile device: Huawei

**Comment by ZB-concordium** [comment]
Verified.
Software Version: 3.0.2 (86)
OS: Android 12
Mobile device: Samsung S21 Ultra
