### ISSUE TITLE
"Lower delegation amount and stay with current pool" changes target pool

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium-reference-wallet-android#153]
**Bug Description**
The new pool is used instead of your current pool.

**Steps to Reproduce**
1. Delegate to pool `A` with `x` CCD
2. Try to delegate to pool `B`, where `x` CCD will bring the pool over one of the two caps.
3. The popup "Current delegation amount too large" is shown. Click on "Lower delegation amount and stay with current pool".
4. Change the amount to be <= the limit for the new pool.
   - The limit pool `B` is shown, which is quite useful
5. Click Continue
6. Look at the target pool in the transaction summary shown

**Expected Result**
Target: `A`, since we are staying in the current pool and lowering the delegated amount

**Actual Result**
Target: `B`
The transaction subsequently fails with "Stake is above maximum threshold", because it tries to move to `B` instead of staying with `A`.

**Versions**
- Software Version: 3.0.0
- OS: Android
- Mobile device: Huawei

**Comment by rimbi** [comment]
Verified with the Android MW version 3.0.11 (95)
