### ISSUE TITLE
Typos in delegation intro flow

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium-reference-wallet-android#154]
**Bug Description**
In the initial introflow for delegation, there were two minor errors:

`therefor` -> `therefore`
`trade off` -> `trade-off`

**Versions**
- Software Version: 3.0.0 (84)
- OS: Android
- Mobile device: Huawei

**Comment by ZB-concordium** [comment]
Verified. 
Software Version: 3.0.2 (86)
OS: Android 12
Mobile device: Samsung S21 Ultra
