### ISSUE TITLE
Total amount is wrong on simple transaction page

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-android#155]
**Bug Description**

**Steps to Reproduce**
Have stake that is delegated.
Attempt to send CCDs.

**Expected Result**
Total amount of CCDs should be all the CCDs except the Shielded ones. (Total = Delegated or Staked+Scheduled+AtDisposal)

**Actual Result**

Total seems to be equal to disposable here:

![image](https://user-images.githubusercontent.com/98821384/169472139-7b8017b0-d712-40c2-8a75-a9e47fc2cc26.png)

**Versions**
- Software Version: 3.0.0 (84)
- OS: Android
- Mobile device: Pixel 4a

**Comment by ZB-concordium** [comment]
Verified.
Software Version: 3.0.2 (86)
OS: Android 12
Mobile device: Samsung S21 Ultra
