### ISSUE TITLE
Informing user regarding funds released after the cooldown period

### ISSUE THREAD

**Issue by XOOPsoft** [Concordium/concordium-reference-wallet-android#156]
Bug Description
If a user reduced the delegation amount or removes funds completely from a pool. User will enter the cooldown period that lasts for "delegator cooldown duration". However, funds are actually released on the next payday. Meaning, funds are released for "delegator cooldown duration" + time to next payday.

Steps to Reproduce
Remove delegation.
Reduce the delegated stake.

Expected Result
Inform the user about releasing funds after the correct time.

Actual Result
Only cooldown time is shown to the user.

This issue is a clone of iOS issue 270:
https://github.com/Concordium/concordium-reference-wallet-ios/issues/270

**Comment by ZB-concordium** [comment]
Verified.
Software Version: 3.0.4 (88)
OS: Android 12
Mobile device: Samsung S21 Ultra
