### ISSUE TITLE
Locked amount can be changed by user

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-android#158]
**Bug Description**
If the user is in cooldown. User can still change the locked amount if user tries to change the pool and try to update amount.
Transaction is rejected, but I feel like locked amount is not supposed to be changeable.

**Steps to Reproduce**
Delegate to pool id 1 -> rewards received.
Remove delegator -> cooldown period starts.
Attempt to update delegation -> change pool to another id.
Tap on the locked amount, increase it +1 -> amount was changed.
Submit transaction.

**Expected Result**
Locked amount is locked.

**Actual Result**
Locked amount can be changed.

**Versions**
- Software Version: 3.0.1 (85)
- OS: Android
- Mobile device: Google Pixel 4a

Video:

https://user-images.githubusercontent.com/98821384/170331074-b0034b26-0f77-49fd-b8c2-02a595fe15a4.mp4

**Comment by ZB-concordium** [comment]
Verified.
Software Version: 3.0.2 (86)
OS: Android 12
Mobile device: Samsung S21 Ultra
