### ISSUE TITLE
Same transaction can be submitted multiple times

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-android#160]
**Bug Description**
It seems that there is something wring in the flow with the back button after transaction was submitted.
The main thing here is that user is not really aware that transaction was being charged and thus get charged three times. Also this is inconsistent with how the simple transactions work. Once simple transaction is submitted, user can't go back, the only thing user can do is select Finish.

The way it is implemented on iOS is as well that there is no back button.

**Steps to Reproduce**
Add delegation to a pool.
After submitted transaction press back.
Repeat first two steps.
Look at the transaction log.

**Expected Result**
This should not be possible. I assume we should remove back button.

**Actual Result**
Back button is present and user can select back after submitted transaction.

**Versions**
- Software Version: 3.0.1 (85)
- OS: Android
- Browser
- Mobile device: Pixel 4a

Video:

https://user-images.githubusercontent.com/98821384/170342739-3873320f-e927-4381-8fd3-b7f170fccc55.mp4

**Comment by ZB-concordium** [comment]
Verified.
Software Version: 3.0.4 (88)
OS: Android 12
Mobile device: Samsung S21 Ultra
