### ISSUE TITLE
Add "Success" notification after successful update of passcode/biometrics

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-android#162]
**Task description**

This task is just to add a simple alert to the UI after a successful update of passcode / biometrics in the app. 

The alert can be seen in Figma on the page called "Second batch of CRs from the UATs".

**Comment by XOOPsoft** [comment]
Investigated in Jira CBW-242.
There is already a Toast message displaying: “Passcode was successfully changed“.
This toast message is enough.
