### ISSUE TITLE
Testnet app installation

### ISSUE THREAD

**Issue by ZB-concordium** [Concordium/concordium-reference-wallet-android#163]
**Bug Description**
After installation the app opens and than crashes. After reopening the app switching between the logo and the "Terms and conditions..."
**Steps to Reproduce**
Install App
Open it

**Expected Result**
I can accept the Terms and condition and go forward with the initial setup

**Actual Result**
Flickering between Testnet logo and "Terms and conditions..."

**Versions**
- Software Version, Concordium Testnet 3.0.2(86)
- OS, Android 12 (OneUI 4.1) Samsung
- Mobile device, Samsung S21 Ultra

**Comment by XOOPsoft** [comment]
@ZB-concordium: I have fixed this in release 3.0.3 (87)

**Comment by ZB-concordium** [comment]
Verified.
Software Version: 3.0.4 (88)
OS: Android 12
Mobile device: Samsung S21 Ultra
