### ISSUE TITLE
Forced update: "Remind me next time I open app" not enforced correctly

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium-reference-wallet-android#165]
**Bug Description**
Related to https://github.com/Concordium/concordium-reference-wallet-android/issues/45

**Steps to Reproduce**
1. Use an app that has been set up
2. Open the app and see the "Update ready" popup
3. Click "Remind me next time I open the wallet"
4. Click on an account, the more tab, backup tab or similar
5. Return to the accounts tab

**Expected Result**
The accounts tab is shown without a popup

**Actual Result**
The "Update ready" popup is shown again.

**Versions**
- Software Version: 3.0.4 (88)
- OS: Android 9
- Mobile device: Huawei

**Comment by XOOPsoft** [comment]
Fixed in version 3.0.5 (89)

**Comment by Bargsteen** [comment]
The solution has been verified. It now works as expected.
