### ISSUE TITLE
Delegation Status - Waiting for transaction to finalize

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-android#166]
**Bug Description**
While adding/updating/removing delegation, if transaction was not finalized, we would see the status page with text "Waiting for transaction to finalize". The problem is that even if transaction gets finalized, status page will not change.
This could make users wait for a long time or thinking that transaction can't be finalized. I believe this will often happen if internet connection is slower or proxy doesn't respond for some reason.

**Steps to Reproduce**
Add delegation -> Submit -> Insert passcode -> Finish -> Confirm dialogue -> Burger menu -> Delegation. 

Such a screen can be visible if user tries to see the Delegation status page while transaction was not finalized after following actions:
- Add delegation.
- Update delegation stake.

**Expected Result**
After transaction was finalized, Delegation status page should be changed accordingly. User should not select back and forth to see the change in the status page. The page will be changed automatically once the transaction is finalized.

**Actual Result**

https://user-images.githubusercontent.com/98821384/171373721-c129951f-0455-4921-8f2e-24026844552d.mp4

**Versions**
- Software Version: 3.0.0 (87)
- OS: Android
- Browser
- Mobile device: Pixel 4a

**Comment by XOOPsoft** [comment]
@mh-concordium 
I think that in the video the transaction is not finalised yet.
If you go back and wait for the two checkmark icons to appear on the transaction line (instead of the clock).
When you see the two checkmark icons, then you open the status page and see the details.

**Comment by jens-concordium** [comment]
I think the point is to poll the wallet-proxy for updates on the transaction once in a while, and then update the screen automatically, so the user doesn't have to browse back and forth.

It's the same on iOS.

**Comment by XOOPsoft** [comment]
Polling is implemented on the account details page.
Do you want it to be implemented on the status page as well?

**Comment by XOOPsoft** [comment]
Ideally in the future this should be send to the devices as a push notification (maybe silent). So polling cam be avoided.
Maybe that is something for the idea bank?

**Comment by ZB-concordium** [comment]
Software Version: 3.0.4 (88)
OS: Android 12
Mobile device: Samsung S21 Ultra

**Comment by XOOPsoft** [comment]
It is fixed in release 3.0.6 (90)

**Comment by XOOPsoft** [comment]
The crash that is mentioned is fixed with release 3.0.8 (92)

**Comment by ZB-concordium** [comment]
Verified
Software Version: 3.0.8 (92)
OS: Android 12
Browser: Chrome
Mobile:  Samsung Galaxy S21 Ultra
