### ISSUE TITLE
Android Stagenet App Crashes when opening delegation menu after delegation

### ISSUE THREAD

**Issue by chrmatt** [Concordium/concordium-reference-wallet-android#167]
**Bug Description**
When I try to open the delegation menu for an account right after choosing delegation for this account, the app restarts.

**Steps to Reproduce**

- Create account.
- Click on More->Delegation and delegate something to some pool
- Click again on More->Delegation

**Expected Result**
Some information about delegation is shown.

**Actual Result**
App crashes.

**Versions**
- Software Version: 3.0.7 (91)
- OS: Android 12
- Browser: Chrome
- Mobile device, if applicable: Samsung Galaxy S21

**Comment by ZB-concordium** [comment]
Software Version: 3.0.8 (92)
OS: Android 12
Browser: Chrome
Mobile:  Samsung Galaxy S21 Ultra
