### ISSUE TITLE
Missing baker ID in baker credentials file

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-android#168]
**Bug Description**
Comparing baker credentials exported by Mobile Wallet and exported by Concordium Client looks different. Baker ID is missing. This will prevent us from actually baking.

**Steps to Reproduce**
Try to add baker with MW on Android -> save baker-credentials.
Add baker with client -> save baker-credentials.
Compare exported baker-credentials.

**Expected Result**
They should look the same otherwise, I assume that node will not accept the file.

**Actual Result**
Baker Id is missing from the file exported by Android.

**Versions**
- Software Version:3.0.9(93)
- OS: Android
- Mobile device: Google Pixel 4a

**Comment by ZB-concordium** [comment]
Verified
Software Version:3.0.10(94)
OS: Android 12
Mobile device: Samsung S21 Ultra
