### ISSUE TITLE
Updating pool settings without any changes ends up with a transaction

### ISSUE THREAD

**Issue by rimbi** [Concordium/concordium-reference-wallet-android#170]
**Bug Description**

Updating pool settings without any changes ends up with a transaction 

**Steps to Reproduce**

1- Update the pool settings such that the pool will be `open for all`
2- Update the pool settings such that the pool will be `closed for new delegators`
3- Update the pool settings without making any changes

**Expected Result**

In the last step, there should be no new transaction but a dialog message displayed which tells there is no need for a new transaction because there is no change.

**Actual Result**

A new configure baker transaction which closes the pool for delegation is submitted.

**Versions**
- Software Version: 3.0.11 (95)
- OS: Android

**Comment by XOOPsoft** [comment]
I am not sure how to reproduce this.
I have tried this:
If I have a baker setup with "Open for delegation", then go into "update pool settings", then just continue all the way through without making any change, I get a popup saying "Notice, your transaction contains no changes..."
Maybe it is possible to record a video?

**Comment by rimbi** [comment]
Apparently you have not applied all the steps. Please read step 2 and 3 again.

**Comment by XOOPsoft** [comment]
Ah ok, it only happens when baker is currently "Closed for new". I will look into this. Thanks!

**Comment by XOOPsoft** [comment]
Fixed in version 3.0.12 (96)

**Comment by rimbi** [comment]
Verified with version 3.0.12 (96)
