### ISSUE TITLE
Incorrect Pool Info displayed  during `Update delegation`

### ISSUE THREAD

**Issue by rimbi** [Concordium/concordium-reference-wallet-android#171]
**Bug Description**

When updating delegation settings if you change your mind to change the baker Id,  old baker id is used and pool info from the old baker id is displayed.

**Steps to Reproduce**

1- Delegate to pool `X`
2- Go to `Delegation status` page
3- Click `Update current delegation`
4- Skip carousel
5- In the `update delegation` page enter the id of baker `Y` into the optional id field and click `Continue`.
6- In the next page you should see the pool info from baker `Y`, which is correct.
7- Go back to the previous page using the arrow in the upper left corner
8- You will see that baker id of `Y` is present in the baker id field
9- Remove the baker id as it is optional and click `Continue`

**Expected Result**
Pool info of the baker `X` should be displayed

**Actual Result**
Pool info of the baker `Y` is displayed

**Versions**
- Software Version: 3.0.11 (95)
- OS: Android

**Comment by rimbi** [comment]
@jens-concordium and @mh-concordium , Can you please verify that the expectation is correct?

**Comment by jens-concordium** [comment]
@rimbi, yes that sounds correct!

**Comment by XOOPsoft** [comment]
Fixed in version 3.0.12 (96)

**Comment by rimbi** [comment]
Verified with version 3.0.12 (96)
