### ISSUE TITLE
Switching from one pool to another with an amount equal to max limit is allowed

### ISSUE THREAD

**Issue by rimbi** [Concordium/concordium-reference-wallet-android#172]
**Bug Description**

Switching from one pool to another with an amount equal to pool limit is allowed but the transaction fails.

**Steps to Reproduce**

1- Have 2 pools `X` with a limit `400K CCD` and `Y` with `200K CCD`
2- Have 2 separate accounts `A` and `B`
3- Using account `A`, delegate `10K` to `Y`
4- Execute the following steps using account `B`
5- Delegate `200K CCD` to `X`
6- Go to Delegation status page
7- Click Update current delegation
8- Skip carousel
9- In the update delegation page enter the id of baker `Y` into the optional id field and click Continue.
10- In the next page don't change anything and click 'Continue'.

**Expected Result**
It should not be possible to submit the transaction.  

**Actual Result**
Transaction is submitted but fails.

**Versions**
- Software Version: 3.0.11 (95)
- OS: Android

**Comment by rimbi** [comment]
@jens-concordium can you validate the expectation, please?

**Comment by XOOPsoft** [comment]
I have just tried to reproduce this.
It is possible to submit the transaction.
In my test the transaction also succeeded.
(I used baker 83980 and 83981 stagenet for testing)

Reading your test steps, I think that the transaction should succeed.
Why do you think that the transaction is supposed to fail ?

**Comment by rimbi** [comment]
updated the steps, please repeat the test @XOOPsoft

**Comment by XOOPsoft** [comment]
I have tested this again. Now with the new build 3.0.12 (96)
With the new build I see this screen in step 10:
![Screenshot_20220621-173946](https://user-images.githubusercontent.com/81175980/174841563-c2d9e2fe-eada-4b87-963f-a3c0352531f2.png)

**Comment by rimbi** [comment]
I expected to see the same behavior as in the case that the amount exceeds the pool limit, where we see a popup with 3 options, one of which is `Lower delegation amount and stah with current pool`.

**Comment by XOOPsoft** [comment]
Fixed in version 3.0.0 (97)
(notice the version-number, it has been decided that only build-number will be increased for the release, not the 3.0.0)

**Comment by rimbi** [comment]
Verified with version 3.0.0 (98)
