### ISSUE TITLE
It should not be possible to return back after transaction is submitted

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-android#173]
**Bug Description**
After removing delegation, user can select back. This is inconsistent with all other transaction pages.

**Steps to Reproduce**
Remove/stop  delegation.

**Expected Result**
Once transaction is submitted, user can only select finish.

**Actual Result**
![image](https://user-images.githubusercontent.com/98821384/174950893-48ba6829-85f6-47f6-a6c6-7829000d1fb7.png)

**Versions**
- Software Version: 3.0.11 (95)
- OS: Android

**Comment by XOOPsoft** [comment]
Fixed in version 3.0.0 (97)
(notice the version-number, it has been decided that only build-number will be increased for the release, not the 3.0.0)

**Comment by XOOPsoft** [comment]
Will be fixed with pass phrase release. Jira CBW-200
