### ISSUE TITLE
"Pool limit will be breached" on passive delegation

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-android#174]
**Bug Description**
There is a bug that can cause the "pool limit to be breached" warning to show on the amounts page in the passive delegation flow.

**Steps to Reproduce**
1. Have an account with some disposal CCDs. 
2. Find a baker pool that doesn't have room for more CCDs in the pool.
3. Start the flow to add delegation on the account from step 1. Try to delegate something to the pool from step 2, and notice how the apps gives you the "Pool limit will be breached" error - this works as intended.
4. Now go back to the screen where you can choose between baker pools and passive delegation (without exiting the flow), and select passive delegation instead.
5. Try to enter whichever amount of CCDs, and notice how it will say "Pool limit will be breached", which shouldn't be possible on passive delegation.

**Expected Result**
The wallet lets you delegate whichever amount to passive delegation.

**Actual Result**
The wallet says that the "Pool limit will be breached" on passive delegation. 

**Versions**
- Software Version: 3.0.0(99)
- OS: Android 10
- Browser
- Mobile device: Huawei P30 Lite

**Comment by XOOPsoft** [comment]
Thanks Jens, I will fix it before Monday.

**Comment by XOOPsoft** [comment]
Fixed in version 3.0.0 (100)

**Comment by jens-concordium** [comment]
Verified in 3.0.0(100)
