### ISSUE TITLE
Updating Delegation - Text informing user is wrong

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-android#177]
**Bug Description**
While updating delegation amount, user is informed with the text as delegation amount will be reduced.

**Steps to Reproduce**
Add delegation.
Update delegation.

**Expected Result**
No text is needed (as implemented in iOS)

**Actual Result**
Text informs user as user is lowering delegation amount. Still, delegation stake is updated correctly.

**Versions**
- Software Version: Mainnet 3.0.0
- OS: Android

**Comment by pablozsc** [comment]
To my suggestion to create a second account and try to delegate from it, i think this is important observation:

I'd already done that and created another account, the initial delegation works fine but when any increases are tried, the same errors are shown.

**Comment by XOOPsoft** [comment]
![Screenshot_1659939162](https://user-images.githubusercontent.com/81175980/183353798-2b907f91-4db2-45de-aa51-ad3dddc56658.png)

**Comment by XOOPsoft** [comment]
This issue has been fixed. It will be published with the next release.
