### ISSUE TITLE
The mobile wallet adds addresses of non-existing accounts to the address book.

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-reference-wallet-android#19]
**Bug Description**

The mobile wallet adds addresses of non-existing accounts to the address book.

**Steps to Reproduce**

Go through identity issuance and provoke a failed identity. That is, complete the verification flow, but make is so that identity verification will fail.

After returning to the wallet, while the identity is still pending, the initial account is added to the address book, where it can be copied.

After identity issuance fails and the initial (pending) account is deleted, the address book is unaffected.

**Expected Result**

The account address is not added to the address book until the identity and the account are confirmed.

**Actual Result**

The initial account address is added to the address book. It is never deleted even after the account is deleted.

**Versions**
- Software Version: 1.0.7
- OS: Android
- Browser: N/A
- Mobile device, if applicable: Samsung Galaxy S7

**Comment by jens-concordium** [comment]
@jensvesti, this seems to be still happening in 1.0.10, on a Huawei P30 Lite with Android 10.
