### ISSUE TITLE
Unknown backend error when navigating to and from pending account.

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-android#21]
**Description**
While waiting for identity issuance (to fail), initial account is shown pending on account page. When clicking on it and then going back to account page, black pop-up box with unknown backend error pops up.

Steps to Reproduce:
see above

**Expected Result**
No pop-up error.

**Actual Result**
Error.

**Versions**
* Concordium Testnet Wallet v1.0.9 (release)(prod_testnet)
* Huawei Y6s, Android 9

**Comment by jensvesti** [comment]
@concordium-cl Is this a persistent and reproducible issue? I cannot seem to reproduce it here.

**Comment by abizjak** [comment]
@jensvesti It was certainly consistent on my device (which is Galaxy S7).

**Comment by concordium-cl** [comment]
@jensvesti I could reproduce it consistently but will have another look now.

**Comment by concordium-cl** [comment]
@jensvesti I've tried now on the same version and same phone but cannot reproduce the issue neither. Strange, as it was very continuously and consistently observed during the last tests. I will close the issue.

**Comment by jens-concordium** [comment]
@jensvesti, @concordium-cl 

This seems to be fixed for initial accounts on my Android phone in the 1.0.10 release, but I just noticed that it happens for regular accounts as well.

**Comment by abizjak** [comment]
I have also experienced this now. I created 6 accounts and after going back to the account screen I got "Unknown backend error" 4 out of 6 times.

My device is Samsung Galaxy S7.

I suspect whether it happens or not has to do with connection latency to the wallet-proxy, so possibly a reliable way to reproduce it would be to introduce delays when testing.
