### ISSUE TITLE
Identity object should be retrieved in the background (also when app is closed)

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-android#26]
[placeholder]

**Comment by jens-concordium** [comment]
I guess this tries to solve the same problems as the "new" last page of the identity issuance flow, letting the user know to check back once in a while. I've drawn up a few suggestions on what that last page could look like, but I think automatic retrieval would be a better solution. Maybe we should discuss what to do.

**Comment by concordium-cl** [comment]
@jens-concordium: This is a backlog placeholder for some future version, it is not in scope for the upcoming release. The last page is in scope now, so your suggestions are relevant for this release and should be included in a new issue and discussed with Mjoelner.

**Comment by jens-concordium** [comment]
@concordium-cl, alright! I'll make issues for the last page then.

**Comment by concordium-cl** [comment]
last page: https://github.com/Concordium/concordium-reference-wallet-android/issues/27

**Comment by concordium-cl** [comment]
Context changed.
