### ISSUE TITLE
New "last" page in identity flow

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-android#27]
**Description**
The current last page in the identity issuance flow can make it seem like the identity and initial account is verified and ready to use. 

It should be clearer that the identity and initial account has in fact just been submitted to the identity provider, and that it might take a while for it to be verified or rejected. 

Besides the improved clarity about the submission, it should also be clearer that the user has to actively return and open the app, to get the response from identity provider. Due to the way it works now, the identity issuance session will time out, causing the identity and initial account to be lost, if the user does not return to the app in time to retrieve the session.

There will be a flow in Figma that describes how to rework the last page of the issuance flow. More info will follow.

**Expected Result**
After finishing the the identity issuance flow, the user should not be in any doubt of what the status of their submission is, and how to the result of the verification process.

**Actual Result**
The status is not clear after the submission, and the user might miss the necessity of coming back to the app to retrieve the issuance session from the identity provider. 

**Versions**
- Software Version: Affects all versions.
- OS: iOS and Android, not specific versions.

**Comment by jens-concordium** [comment]
Verified in 1.0.12
