### ISSUE TITLE
The app crashes if sending funds from the main screen

### ISSUE THREAD

**Issue by Radiokot** [Concordium/concordium-reference-wallet-android#271]
Send token receipt screen, when the "Finish" button is pressed, "goes back" to the account details screen by launching it with the `FLAG_ACTIVITY_CLEAR_TOP` flag. Not only this causes incorrect navigation when sending funds from the token details screen, but also crashes the app when sending funds from the main screen (accounts overview). In the second case, there is no account details screen instance, and the given intent can't launch one due to missing extras.

https://github.com/Concordium/concordium-reference-wallet-android/blob/93c302d72dd278e221b783fabc8c747c675a1ae1/app/src/main/java/com/concordium/wallet/ui/cis2/SendTokenReceiptActivity.kt#L96-L101

**Comment by ali-concordium** [comment]
@Radiokot Thank you. We are currently working on a patch release, which will be released in 2 weeks. We will include a fix for this.

**Comment by czerwix** [comment]
pushed a PR with a fix https://github.com/Concordium/concordium-reference-wallet-android/pull/282

**Comment by SRConcordium** [comment]
The fix is verified OK and will be included in next release, version 1.3.0
