### ISSUE TITLE
Update text shown in failed identity issuance dialog and e-mail

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-android#31]
**Description**
The text shown in the dialog when identity issuance fails in the mobile wallet should be updated a bit.

When an e-mail client is found, the text should now mention that Concordium is also added to CC. If an e-mail client is not found, it should be added that Concordium can optionally be added to CC. Additionally, when an e-client is not found, the manual copy function, should copy the full text that would have automatically entered in the e-mail.

The text added to the automatically generated e-mails should also be updated to include a bit more info, like app version and which OS the app is running. iOS / Android should be enough, but if possible the specific OS version would be nice as well.

The change can be seen in Figma in flow 21. The semi transparent pages does not have any changes.

**Comment by jens-concordium** [comment]
@jensvesti - After talking with Kristiyan, I have made a small update to the Figma page. If an e-mail client is not found on the phone, the page showing the failed identity should look a little bit different:

![image](https://user-images.githubusercontent.com/76045015/137466275-92757c16-3e76-420e-b322-d05f2fcc5815.png)


There is a bit more explanatory text in the Figma flow, and Kristiyan will also know about the change.

**Comment by jens-concordium** [comment]
This is verified and working as intended in 1.0.14.
