### ISSUE TITLE
Testnet GTU drop amount is incorrect

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-android#32]
**Bug Description**

The app assumes that the testnet GTU drop amount is 100GTU, but it has been updated in the wallet proxy to 2000GTU.

**Steps to Reproduce**
Create an account on testnet. Open the balance.

**Expected Result**
The testnet drop button should show 2000GTU, and the pending drop transaction should also show as 2000GTU.

**Actual Result**
They show as 100GTU, until the transaction is confirmed (at which point it corrects to 2000GTU).

**Versions**

**Comment by concordium-cl** [comment]
Change to 2000 for now.

**Comment by jensvesti** [comment]
@concordium-cl Isn't this fixed in latest?

**Comment by concordium-cl** [comment]
@jensvesti: Oh sorry, could be. I wasn't aware that it was in scope already. I don't have my Android today but will test tomorrow.

**Comment by jensvesti** [comment]
@concordium-cl It wasn't in scope - I just fixed it when I discovered it. A simple text.

**Comment by concordium-cl** [comment]
Great. I've checked, all good in 1.0.11. Thanks!

**Comment by concordium-cl** [comment]
**Fixed in 1.0.11.**
