### ISSUE TITLE
Addresses added multiple times in address book

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium-reference-wallet-android#36]
**Bug Description**

When creating an account, its address is sometimes added multiple times in the address book. It seems like it occurs most frequently when the account creation is slow. I've seen everything between one and five entries per address.

**Steps to Reproduce**
1. Create a new account `X`
2. Wait for it to be finalized
3. View the address book

**Expected Result**
The account `X` has a single entry in the address book.

**Actual Result**
The account `X` has one to five entries in the address book.

**Versions**
- Software Version: 1.0.12 (51)
- OS: Android 9.1.0
- Browser
- Mobile device:  Huawei Y6s

**Comment by jens-concordium** [comment]
I tried on two phones, and I could not reproduce this in 1.0.14.
