### ISSUE TITLE
Investigate automatic synchronization for Android.

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-android#37]
**Description**
There was a support issue for ios that automatic synchronization between two phones does not include decryption key. This scenario must be investigated in Android as well. For more details, see [related iOS issue](https://github.com/Concordium/concordium-reference-wallet-ios/issues/78).

Expected Result
Synchronization includes all keys.

Actual Result
Synchronization does not backup all keys.

**Comment by jens-concordium** [comment]
I was able to do a manual backup on a Pixel 4 with Android 11. The app doesn't get backed up, but the data does. So when the app is installed again, it was possible to access my data. So it seems to work.

Verified in 1.0.16.
