### ISSUE TITLE
Notification on succesful new account

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-android#38]
**Description**
Currently when an account is finalized, the user is not given any explicit notification. People have been asking for more explicit notifications, and while we cannot push notifications to the OS at the moment, we could show one inside the app after polling the wallet proxy.

This notification could also be used to suggest that people should make a backup after a new account has been added, just to encourage backups more often. 

So the suggested change would be:
- Show a pop-up when an account has finalized, that also reminds the user to make a backup. The backup then has two buttons that say "Okay" and "Make backup". Okay will just close the pop-up and leave the user on the current page, and Make backup would take them to the export flow.

Sketches showing can be found in Figma.

**Versions**
- Software Version: 1.0.13
- OS: Android

**Comment by jens-concordium** [comment]
@jensvesti @concordium-cl 

It doesn't seem to work with initial accounts, but regular accounts seem to work relatively well.

I'm pretty sure I made it crash with a notification once, and at one point it also seemed to spam "individual" notifications instead of batching them, after having submitted a bunch of accounts, but I haven't been able to reproduce these things since.

**Comment by jensvesti** [comment]
> @jensvesti @concordium-cl
> 
> It doesn't seem to work with initial accounts, but regular accounts seem to work relatively well.
> 
> I'm pretty sure I made it crash with a notification once, and at one point it also seemed to spam "individual" notifications instead of batching them, after having submitted a bunch of accounts, but I haven't been able to reproduce these things since.

The initial account was missing, but added in next build. 
The crash I haven't seen here and would need more input. 
Individual messages should only happen if you dismiss one, and the next account is finalised right after. Else existing popup should be updated.

**Comment by jens-concordium** [comment]
Verified in 1.0.15.
