### ISSUE TITLE
Support for load balancing cookies

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-android#40]
**Task description**
[placeholder]

**Sub-tasks**
- [ ] subtask 1
- [ ] subtask 2
- [ ] subtask 3

*Add label for component and priority.*

**Comment by concordium-cl** [comment]
Developed on mobil app side. Not developed on devops side, so we cannot test it for this release.

I will move issue to backlog to not forget task.

**Comment by XOOPsoft** [comment]
This has already been implemented on release 3.0.0
And also in new app version 1.0.0
