### ISSUE TITLE
Support for more identity providers

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-android#43]
**Task description**
Add support for another identity provider.

**Sub-tasks**
- [ ] change hardcoded contact info in support dialog when id fails (wallet-proxy)
- [ ] potential changes to id flow?

**Comment by jens-concordium** [comment]
@concordium-cl, @jensvesti - Findings from testing in v1.0.18:

If I install a previous version (e.g. 1.0.16), force a failed identity, leave the failed identity card in the app and then update to 1.0.18, pressing the "Contact Support" button on the failed identity in 1.0.18 will make the app crash.

Else it seems to work as intended. Export and importing between various versions also seem to work fine.

**Comment by concordium-cl** [comment]
Verified normal handling and upgrade from 1.0.16 to 1.0.19. Note that in the latter, the email will state the new version, even though the identity failed in the old version. This cannot be changed but support should be aware of it.
