### ISSUE TITLE
Pending shielding/unshielded transaction are not shown in the shielded balance log.

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-android#49]
**Bug Description**
When making a shielding or an unshielding transaction, the pending transaction is not shown in the log of the shielded balance. The transaction does appear as intended in the log of the regular balance as intended, but ideally it would also be shown in the shielded balance log, while it's pending. 

When the transaction is finalized, it is shown correctly in both logs.

Additionally, when making an unshielding, the amount is shown as negative in the regular balance, while it is pending. The amount should be positive in the regular balance and negative in the shielded balance, as it is added to the regular balance and deducted from the shielded balance. 

**Steps to Reproduce**
- Make a shielding or an unshielding transaction. 
- Check the shielded balance while the transaction is still pending, and notice how the transaction is not shown. 
- Also check the regular balance, and see that the pending transaction can be seen there. If you made an unshielding, notice how the amount is negative while pending in the regular balance log, while it should be positive.

**Expected Result**
- Pending shielding and unshielding transactions **can** be seen in the shielded balance log.
- Pending unshielding transactions are shown as positive in the regular balance log, unless the fee is larger than the amount unshielded.

**Actual Result**
- Pending shielding and unshielding transactions **cannot** be seen in the shielded balance log.
- Pending unshielding transaction are shown as negative in the regular balance log.

**Versions**
- Software Version: 1.0.14
- OS: Android 12

**Comment by concordium-cl** [comment]
Will move.
