### ISSUE TITLE
Show terms and conditions again after update, if the T&C has changed

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-android#59]
**Task description**

At the moment the user is not shown the T&C after an update to the app, that also updated the T&C. 

Each time the T&C has been updated, the user should be shown the new one upon opening the app. However, we might have to let the user make an export, so they don't get locked out if they for some reason don't agree with the new T&C.

**Comment by jens-concordium** [comment]
This works on the Pixel 4 with Android 11 in v1.0.18. @concordium-cl maybe good to double check on your Android phone as well.

**Comment by concordium-cl** [comment]
Verified on Huawei y6s, Android 9, CCD app v.1.0.18.
