### ISSUE TITLE
Rename GTU or G to CCD or C, respectively

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-android#63]
**Description**

**Steps to Reproduce**

**Expected Result**

**Actual Result**

**Versions**
- Software Version
- OS
- Browser
- Mobile device, if applicable

**Comment by jens-concordium** [comment]
As far as I can tell, this is changed everywhere as intended. @concordium-cl, maybe good to get a second pair of eyes to confirm?

**Comment by concordium-cl** [comment]
Yes, looks very good.
