### ISSUE TITLE
Investigation: Returning id object asks user in which app he wants to proceed in

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-android#64]
**Bug Description**
If different *net versions of the app are installed, returning the id object asks the user in which app he wants to proceed in. If the user chooses the right app, it works. If he chooses the non-matching app, the identity flow doesn't complete and the app hangs. After restart, the identity seems to have vanished from (both) apps, which is probably the most sensitive thing to do.

**Steps to Reproduce**
- have mainnet and testnet app installed on device
- issue real-life identity

**Expected Result**
Identity flow completes.

**Actual Result**
User is asked in which app the identity object should be returned.

![IMG_4782](https://user-images.githubusercontent.com/69570978/142388020-bba8974f-69c3-47d6-9629-7e2d5495e0b6.jpg)

**Versions**
- Concordium wallets 1.0.15 and 1.0.16
- Android 9
- Huawei y6s

**Comment by jensvesti** [comment]
@concordium-cl Can you confirm this is only an issue with mainnet and testnet builds, and not staging?

**Comment by concordium-cl** [comment]
@jensvesti: Yes, I can confirm. I only encountered it after the Notabene flow, which is not available on stagenet.

**Comment by jens-concordium** [comment]
@jensvesti @concordium-cl, this still pops-up if both the Mainnet and CryptoX apps are installed. Testnet and Stagenet are no longer on the list of options, if they are installed.

**Comment by concordium-cl** [comment]
Fixed in CCD testnet/mainnet 1.2.1 (64).
