### ISSUE TITLE
Investigation: Initial credential missing in export

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-android#65]
**Bug Description**
I have created an id and initial account. Then did an export. The credential is not included in the account, so I cannot e.g. import to the concordium-client (`Error: Cannot import accounts: cannot decrypt wallet export: cannot decode JSON: Error in $.identities[1].accounts[0]: key "credential" not found.`). The account is functional though, I can send, shield etc. 

I then reinstalled the app. New id/account creations and export work. I can also reimport the previous export. After that, the account is not marked as initial account.

**Steps to Reproduce**
Unclear. But export file exists on [drive](https://drive.google.com/file/d/1zgkSYyRCYFKyGzGRJ1I-YJZppLuikSGG/view?usp=sharing)

**Expected Result**
Credential is included in the export.

**Actual Result**
Credential is missing in the export file.

**Versions**
- Android 9
- Huawei 6ys
- Stagenet
- Concordium stagenet 1.0.16

**Comment by jensvesti** [comment]
@concordium-cl Unable to reproduce. Can you reproduce this consistently?

**Comment by jensvesti** [comment]
As discussed, this does not have priority for now.

**Comment by concordium-cl** [comment]
Unreproducible.
