### ISSUE TITLE
Changing passcode does not work without biometrics enabled

### ISSUE THREAD

**Issue by shjortConcordium** [Concordium/concordium-reference-wallet-android#67]
**Bug Description**

On the current Stagenet build (1.0.16), I get some bugs when changing password, on a phone without bio-metrics/fingerprint enabled.
1. After verifying the new password, I am sent to the "Are you new here?" page from the initial flow.
2. Whenever I try to do anything that uses the existing private keys (like exporting or sending a transfer), I get an "unexpected encryption/decryption error".
3. If I create a new identity, the new accounts will work.
4. If I close the app, and start again, It is the old password, which is accepted to unlock the app. And the old accounts now work again, while the new accounts now get the "unexpected encryption/decryption error".

**Steps to Reproduce**
- Have a phone without bio-metrics enabled.
- Have the app installed, with at least 1 account in it.
- Change the pass-code.
- Send a transfer from your account

**Expected Result**

- I am able to send the transfer, using the new password.

**Actual Result**

- I am unable to send the transfer, due to an "unexpected encryption/decryption error".

**Versions**
- v1.0.16 (Stagenet build)
- Android 9 (without fingerprint enabled)
- Samsung J5 2017

**Comment by concordium-cl** [comment]
Verified in stagnet ccd app v1.0.19.
