### ISSUE TITLE
Let user remove non-existing accounts and incorrectly verified identities

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-android#69]
**Description**'

**So far this has only been a problem on iOS, but we should consider doing this on Android as well, just in case.** 

Some users have experienced that their initial accounts don't exist in the chain, even though the seem perfectly fine and verified in the iOS wallet. This is due to incorrectly verified identities, that shouldn't in fact have been verified. 

This problem was solved in a later version of the wallet, but the initial accounts and identities remain and cannot be removed because the wallet thinks they are working as intended. 

We should add an option to let the user make a check of accounts and identities, to see if they in fact exist. If the check reveals that the account does not exist on the chain, we should let the user remove the account and related identity. _If the account does exists, the option to remove it should not be there._

**Comment by concordium-cl** [comment]
Support case description below added after slack discussion:

1. **iOS: Account exists in wallet but not on chain.** Other accounts cannot be created with same identity.

2. **Android: Account does not exist in wallet but on chain.**  Account is added to address book before finalization, so users copied address there. Account then finalized and was created on chain. However, user never picked up the id object, so account was not created in wallet itself.

3. **iOS: Account exists in address book in wallet and on chain but not on account page**: Lately, we had a support case on iOS, where it seems that the account is in the address book and does exist on chain. But it is not on the account page in the wallet. The related identity object seems to have failed. The case is not entirely clear nor proven.

**Comment by concordium-cl** [comment]
Needs thorough consideration, which cases to handle.

**Comment by concordium-cl** [comment]
Will check.
