### ISSUE TITLE
Investigation: Make it easier to export to local file system

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-android#70]
**Description**

If possible, it would be nice to be able to always choose to save exports to the local file system. Some users experience not being able to save locally, and only can export via e.g. chat and e-mail apps. 

There are however some users who have no problem exporting using their file browsers, so the problem might be with the individual phones. 

**Versions**
- Software Version: ??
- OS: Android

**Comment by concordium-cl** [comment]
@jensvesti: Could you briefly describe your findings?
