### ISSUE TITLE
After app upgrade, backup nagging box reappears after export

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-android#84]
**Bug Description**
When the CCD app is upgraded to newest version, the backup nagging box `Some accounts are not backed up. Press here to back them up.` reappears after export when switching through tabs `Accounts `and `Identities`.

Note that with a clean new install (no upgrading) it works as expected, i.e. no reappearing of nagging box after export.

**Steps to Reproduce**
- create an account in released version 1.0.22(61)
- upgrade to newest version 1.2.3(66)
- answer `not now` to the new `welcome back, make backup` dlg, then `dismiss` in the follow-up dlg
--> backup nagging box appears

- make an export (either by pressing the nagging box or via More menu)
--> backup nagging box disappears

- switch between tabs Accounts and Identities
--> backup nagging box appears again

**Expected Result**
Backup nagging box disappears after export until a new account is created.

**Actual Result**
Backup nagging box disappears after export but comes back after switching tabs.

**Versions**
- 1.0.22(61) --> 1.2.3(66)
- Android 9
- Huawei Y6s

**Comment by jensvesti** [comment]
@concordium-cl The bug was simple. Showing the popup due to an update would set the "backup has been done" flag to false regardless.

**Comment by concordium-cl** [comment]
Verified on testnet CCD v.1.2.5(68).
