### ISSUE TITLE
First released version 1.0.7 cannot be installed anymore

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-android#85]
**Bug Description**
After deleting newest testnet app v1.2.3(66), first released version 1.0.7 cannot be installed anymore. It fails with message `App not installed`, as if you'd try to downgrade from a newer version to an older version. Do we not delete all data?

Or can the old version not be installed by different reasons?

**Steps to Reproduce**
- install v1.2.3(66)
- delete it
- install v1.0.7

**Expected Result**
Old version can be installed.

**Actual Result**
Old version cannot be installed; `App not installed`

**Versions**
- see above
- Android 9
- Huawei Y6s

**Comment by jensvesti** [comment]
@concordium-cl I see this from time to time. It hasn't been related to the actual build, but a hiccup in the OS itself. Restarting the phone may help, or try install the new version and uninstall it again may help. Using ADB (Android Debug Bridge - a command line tool that comes with eg. Android Studio) to uninstall may also be an option, as sometimes it isn't uninstalled although up cannot see the app. Uninstalling and installing through ADB may reveal more info as to why it cannot install/uninstall on the particular phone.

**Comment by concordium-cl** [comment]
Restarting phone and installing newest version did not work. Used v1.0.8 for testing now, which was released internally very soon after 1.0.7.
