### ISSUE TITLE
Update simple and shielded transaction flows

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-android#89]
**Task description**

The transaction flows for the simple and shielded transaction should be updated a bit. 

The first need-to-have update is a new option to just paste a recipient address, while the user should also be able to scan a QR code or look up addresses in the address book. 

The second need-to-have update is an update to the available funds area shown at the top. As the shielded balance will be hidden as default, the shielded balance shouldn't be mentioned at the top of the transaction page. Instead it should show the public balance total, and the amount at disposal. 

The two need-to-have updates are highlighted in the screenshot below. The full flow can be seen in "Flow 1" and "Flow 4" here: https://www.figma.com/file/pUlYPsHRU0Hvm0NoGIvxrv/Mobile-Wallet?node-id=2881%3A13697

You will see that the flows contain other changes compared to what we have now, but these are nice-to-have and will be described in another issue. 

![image](https://user-images.githubusercontent.com/76045015/151314912-44d347ed-aef1-4192-bef7-2f6cd805c90b.png)

**Comment by mh-concordium** [comment]
Verified.

Balances are still wrong as stated here: https://github.com/Concordium/concordium-reference-wallet-android/issues/102
Retesting balances together with verification of that bug.

**Versions**
- Software Version: Testnet 2.0.1 (71)
- OS: Android 11
- Browser: N/A
- Mobile device: Pixel 4a
