### ISSUE TITLE
Add "Send all" and styling updates for transaction flows

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-android#90]
**Task description**

The simple and shielded transaction flows are being update with new necessary features in #89 . In relation to that there are a few nice-to-have updates to the transaction flows. Those are:

- Addition of a "Send all" button, that takes everything available for transactions minus the estimated transaction fee, so the user can easily move all available funds from an account.
- Some UI changes to flatten the UI.

The nice-to-have changes can be seen in the screenshot below, and the full flows can be seen in "Flow 1" and "Flow 4" here: https://www.figma.com/file/pUlYPsHRU0Hvm0NoGIvxrv/Mobile-Wallet?node-id=2881%3A13697

**Important!** Please coordinate between between iOS and Android development, so these nice-to-have changes are only done, if there is time to do them on both platforms. 

![image](https://user-images.githubusercontent.com/76045015/151316415-1f9b78bd-9d9a-48a8-9d18-5a873dffbeaa.png)

**Comment by mh-concordium** [comment]
Verified.

**Versions**
- Software Version: Testnet 2.0.1 (71)
- OS: Android 11
- Browser: N/A
- Mobile device: Pixel 4a
