### ISSUE TITLE
Hide the identities page + redesign of navigation bar.

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-android#92]
**Task description**

After the user has their first verified identity, there is not much reason to keep it as such a prominent part of the UI. Some users even thought the identity was their account, so it was decided to move the identities page from the navigation bar to the more menu, as way to make the identities less prominent in the UI.

As the identities will no longer be part of the navigation bar, there is instead room for a direct path to make a backup. The new navigation bar and More page can be seen below in the screenshot, or in "Flow 8" in Figma. 

![image](https://user-images.githubusercontent.com/76045015/152167942-85a6ecd3-b1f2-437b-bd59-544831baaa50.png)

Notes:
- Export is also going to be renamed "Make backup" and Import is going to be renamed to "Restore backup".

**Comment by mh-concordium** [comment]
Verified.

For I have created a bug for the issue mentioned in comments https://github.com/Concordium/concordium-reference-wallet-android/issues/133

**Versions**
- Software Version: Testnet 2.0.1 (71)
- OS: Android 11
- Browser: N/A
- Mobile device: Pixel 4a
