### ISSUE TITLE
Dialogues about account being ready and warning about the backup keep appearing even after the backup was created

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-android#93]
**Bug Description**
Dialogues about account being ready and warning about the backup keep appearing even after the backup was created. This happens after user rotates screen. I have noticed that this issue appears after initial installation and wallet setup. I was not able to reproduce the bug once I have restarted the application.

**Steps to Reproduce**
1. Install Concordium Wallet using staging apk.
2. Create account and identity.
3. Select Continue once Identity is ready.
4. Select on Balance and back will trigger the dialogue "Your new account is ready!" -> Select OKAY
5. "Warning" regarding backup pops up.
6. Select MAKE BACKUP.
7. Send the backup file via email.
8. Rotate screen to landscape mode

**Expected Result**
UI should change orientation.

**Actual Result**
UI changes the orientation to landscape mode but "Your new account is ready!" ad "Warning" dialogs keep popping up after the rotation.

**Versions**
- Software Version: 1.2.6 (69)
- OS: Android 10
- Browser
- Mobile device, if applicable: Samsung Galaxy J6
-Attachment - video:

https://user-images.githubusercontent.com/98821384/152166373-73e44a17-c332-44f4-af09-f164bf5fe5ad.mp4

**Comment by XOOPsoft** [comment]
As the app is at the moment it not possible to rotate. At some point it has been decided that all screen are only available in portrait mode. So the bug is not reproducible at the moment. However I have still made sure in the code that this cannot happen later if it is decided to enable landscape mode again.

**Comment by ZB-concordium** [comment]
If I rotate my phone nothing happens...
Software Version: 3.0.5 (89)
OS: Android 12
Mobile device: Samsung S21 Ultra

**Comment by XOOPsoft** [comment]
True. At some point the app code was changed so that the app can only run in portrait mode.
I was changed by the former developer, so I don't know why that was decided. Portrait mode only was introduced from app version 2.0.2 (72). So the bug is not relevant at the moment.

**Comment by ZB-concordium** [comment]
Thank you.
