### ISSUE TITLE
Update the "totals areas"

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-android#94]
**Task description**

As we are going to need some changes in the totals area at the top of the account pages in related to the hiding the shielded balance in #91 and the coming delegation updates, we need to make some general updates to the totals areas.

All the changes to both the totals area of the general account page and the account specific totals area can be seen in Flow 9 in Figma. 

Each screen has a small description of the specific scenario.

Notes:
- When an account is a baker, it will say "Stake with baker 'bakerID'" in the totals area. In the future, when an account can delegate an amount, this string can be "Delegation with baker 'bakerID'". It might not matter now, so this can be disregarded for now if it makes no difference for how it's implemented.

**Comment by mh-concordium** [comment]
Verified, however the [bug](https://github.com/Concordium/concordium-reference-wallet-android/issues/102) needs to be fixed.

MW version: 2.0.
OS: Android 11.
Device: Google Pixel 4a.
