### ISSUE TITLE
New button styling

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-android#95]
**Task description**

In some of the need-to-have flows, new styling of the  "Send", "Shield", "Unshield", "Send (shielded) and "Receive" buttons can be seen. This styling change is nice to have with low-priority. 

The new styling can be seen in the screenshot below and e.g. in Flow 3 in Figma. 

**Important!** Please coordinate between between iOS and Android development, so these nice-to-have changes are only done, if there is time to do them on both platforms. 

![image](https://user-images.githubusercontent.com/76045015/152171257-fb46aadb-5da4-4dcb-bc83-13b8d4a1d179.png)

**Comment by mh-concordium** [comment]
Verified.

**Versions**
- Software Version: Testnet 2.0.1 (71)
- OS: Android 11
- Browser: N/A
- Mobile device: Pixel 4a
