### ISSUE TITLE
New flat styling of the transaction log

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-android#96]
**Task description**

In some of the need-to-have flows a new flat style for the transaction log can be seen. This is a nice to have task with low priority. 

The new flat design can e.g. be seen in Flow 3, or in the screenshot below. 

**Important!** Please coordinate between between iOS and Android development, so these nice-to-have changes are only done, if there is time to do them on both platforms. 

![image](https://user-images.githubusercontent.com/76045015/152172066-bb10aaf8-652f-4910-a4a4-415d71679c9d.png)

**Comment by mh-concordium** [comment]
Verified.

**Versions**
- Software Version: Testnet 2.0.1 (71)
- OS: Android 11
- Browser: N/A
- Mobile device: Pixel 4a
