### ISSUE TITLE
New flat styling of ID cards

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-android#97]
**Task description**

In Flow 7 in Figma a new flat styling for the identity cards can be seen. This is nice-to-have with low priority. Besides being flat, the ID cards now also have coloured edges matching their status a bit. 

**Note:** As you can see in one of the screenshots below, the ID cards can be seen besides an account card in the intro flow. This means that if the ID card is made flat, the account cards have to be flat as well. 

**Important!** Please coordinate between between iOS and Android development, so these nice-to-have changes are only done, if there is time to do them on both platforms. 

The new styling can also be seen in the screenshots below:
![image](https://user-images.githubusercontent.com/76045015/152173066-0490b1b8-eae0-4740-b063-79098656c7f1.png)
![image](https://user-images.githubusercontent.com/76045015/152173101-d94085d4-0230-47bf-9526-360a612a69e0.png)
![image](https://user-images.githubusercontent.com/76045015/152173135-f18c50fd-11e8-46ea-a9b8-342990e04212.png)

**Comment by mh-concordium** [comment]
Verified.

**Versions**
- Software Version: Testnet 2.0.1 (71)
- OS: Android 11
- Browser: N/A
- Mobile device: Pixel 4a
