### ISSUE TITLE
It seems like autofill capability for 2FA floats while user needs to provide password

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-android#98]
**Bug Description**
Auto-fill capability which floats while user needs to provide password is for 2FA. If user tries to use this auto-fill, it seems that application expects to receive a code.  I have attached the video.

**Steps to Reproduce**
1. Install Concordium Wallet.
2. Create account and id.
3. Restart application.

**Expected Result**
User should provide the password on a startup. Since the user interface on a startup is for providing password, it is expected that auto-fill doesn't float (can't be enabled). It shouldn't be available, unless we store passwords somewhere and want to use that auto-fill capability.

**Actual Result**
Auto-fill button floats on the startup and If auto-fill is selected, it seems that application expects 2FA code where user would normally just type in the password.

Attached video:

https://user-images.githubusercontent.com/98821384/152222197-5d8e01b0-bac1-4e15-a97b-796f91d8ba82.mp4

**Versions**
- Software Version: 1.2.6 (69)
- OS: Android 10
- Browser
- Mobile device: Samsung Galaxy J6

**Comment by mh-concordium** [comment]
I believe its some kind of Android built in functionality. I didn't do anything specific to enable it, it was just there.
If you can't reproduce it, please just move it back to 'ready to test' and then we can try again.

**Comment by XOOPsoft** [comment]
@mh-concordium 
Please try to see if you reproduce. If you can, then maybe I can borrow that device, when I come to your office.

**Comment by ZB-concordium** [comment]
Verified.
Software Version: 3.0.2 (86)
OS: Android 12
Mobile device: Samsung S21 Ultra

But on Samsung ONE UI 4 the autofill not existing...at least not in that from like the example video. Fingerprint log in, Samsung pass, and passcode with keyboard pops up.
