### ISSUE TITLE
Mobile Wallet stops working if password on a startup was not re-entered

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-android#99]
**Bug Description**
This bug appears in possibly rare use case. It appears if the initial flow of creating password was interrupted in a way that password was never re-entered. Mobile Wallet can't recover, it has to be reinstalled completely.

**Steps to Reproduce**
1. Install Mobile Wallet.
2. In "Select Passcode" dialogue, type in 6 digits.
3. New dialogue "Re-enter Passcode" opens.
4. Stop application (Android more menu to list the apps and close it).
5. Start application again.
6. "Enter Password" dialogue opens.
7. Type in 6 digits and select Continue.
8. Select Continue.

**Expected Result**
I am not sure what is expected, I assume that flow of creating a password should be restarted in this case.

**Actual Result**
Application stops.

Attached video:

https://user-images.githubusercontent.com/98821384/152296587-5f110b4e-30a1-4447-9034-7dd41fdf9141.mp4

**Versions**
- Software Version: 1.2.6 (69)
- OS: Android 10
- Browser
- Mobile device, if applicable: Samsung Galaxy J6

**Comment by ZB-concordium** [comment]
Software Version: 3.0.6 (90)
OS: Android 12
Mobile device: Samsung S21 Ultra

It is working also after the force stop.
